
version: "3"

services:
    grafana:
        image: grafana/grafana
        container_name: grafana
        user: "0:0"
        ports:
            - 3000:3000
        volumes:
            - ./data/grafana:/var/lib/grafana

    prom:
        image: prom/prometheus
        container_name: prometheus
        ports:
            - 9090:9090
        volumes:
            - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    node-exporter:
        image: prom/node-exporter:latest
        container_name: node-exporter
        ports:
            - 9100:9100
    db:
      image: mysql:5.7
      container_name: project_name_mariadb
      restart: always
      volumes:
        - data:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3306:3306"
      healthcheck:
        test: ["CMD", "mysql", "-h", "${DB_HOST}", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"] 
        timeout: 20s
        retries: 10
    django:
        image: bandhu8/hello:latest
        container_name: django
        ports:
            - 8000:8000
            - 50000:50000
        env_file:
            - .env
        depends_on:
             db:
               condition: service_healthy
volumes:
   data:  