version: "3"

services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "0:0"
    ports:
      - 3000:3000
    volumes:
      - ./provisioning/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./provisioning/grafana/dashboards:/etc/grafana/provisioning/dashboards

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./provisioning/prometheus:/etc/prometheus

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - 9100:9100

  db:
    image: mysql:8.0.11
    container_name: project_name_mariadb
    restart: always
    volumes:
      - .data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "${DB_HOST}", "-u", "root", "-p${DB_ROOT_PASSWORD}", "-e", "SELECT 1"]
      timeout: 20s
      retries: 10

  django:
    image: bandhu8/hello:latest
    container_name: django
    command: sh -c "sleep 10 && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - 8000:8000
      - 50000:50000
    env_file:
      - .env
    depends_on:
      - db 
  backup:
    image: alpine
    container_name: mysql_backup
    volumes:
      - .data/mysql-backups:/backups
    environment:
      MYSQL_CONTAINER: project_name_mariadb
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    entrypoint: >
      sh -c "
      echo '0 0 * * * root /usr/bin/mysqldump -h ${DB_HOST} -u ${DB_USER} -p${DB_PASSWORD} ${DB_NAME} > /backups/db_backup_$(date +\%F).sql' >> /etc/crontabs/root &&
      crond -f -d 8
      "
    depends_on:
      - db     # Ensure db service is started before django

volumes:
  data: