{
 "title": "todo metrics",
 "tags": [
  "django",
  "mysql"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Node Filesystem file",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "node_filesystem_files", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total status created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "django_http_responses_total_by_status_created",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes buckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "django_http_requests_body_total_bytes_bucket",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}