global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node-exporter'
    static_configs:
      - targets:
        - node-exporter:9100  # Replace with your node-exporter service name and port

  - job_name: 'django-app'
    static_configs:
      - targets:
        - django:8000  # Replace with your Django service name and port



